SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Databases
-- ----------------------------
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_0 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_1 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_2 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_3 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_4 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_5 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_6 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS cloud_mall_recommend_7 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- ----------------------------
-- product_favorites tables (8 DB x 16 tables)
-- ----------------------------
USE cloud_mall_recommend_0;
CREATE TABLE IF NOT EXISTS product_favorites_0 (
  id bigint(20) NOT NULL,
  user_id bigint(20) NOT NULL,
  product_id bigint(20) NOT NULL,
  create_user_id bigint(20) DEFAULT NULL,
  create_user_name varchar(64) DEFAULT NULL,
  create_time datetime(3) DEFAULT NULL,
  update_user_id bigint(20) DEFAULT NULL,
  update_user_name varchar(64) DEFAULT NULL,
  update_time datetime(3) DEFAULT NULL,
  is_del tinyint(4) DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_user_id (user_id),
  KEY idx_product_id (product_id),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE product_favorites_0;

USE cloud_mall_recommend_1;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

USE cloud_mall_recommend_2;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

USE cloud_mall_recommend_3;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

USE cloud_mall_recommend_4;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

USE cloud_mall_recommend_5;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

USE cloud_mall_recommend_6;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

USE cloud_mall_recommend_7;
CREATE TABLE IF NOT EXISTS product_favorites_0 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_1 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_2 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_3 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_4 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_5 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_6 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_7 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_8 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_9 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_10 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_11 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_12 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_13 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_14 LIKE cloud_mall_recommend_0.product_favorites_0;
CREATE TABLE IF NOT EXISTS product_favorites_15 LIKE cloud_mall_recommend_0.product_favorites_0;

-- ----------------------------
-- product_view_record tables (8 DB x 64 tables)
-- ----------------------------
USE cloud_mall_recommend_0;
CREATE TABLE IF NOT EXISTS product_view_record_0 (
  id bigint(20) NOT NULL,
  user_id bigint(20) NOT NULL,
  product_id bigint(20) NOT NULL,
  view_count int(11) DEFAULT 1,
  create_user_id bigint(20) DEFAULT NULL,
  create_user_name varchar(64) DEFAULT NULL,
  create_time datetime(3) DEFAULT NULL,
  update_user_id bigint(20) DEFAULT NULL,
  update_user_name varchar(64) DEFAULT NULL,
  update_time datetime(3) DEFAULT NULL,
  is_del tinyint(4) DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_user_id (user_id),
  KEY idx_product_id (product_id),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE product_view_record_0;

USE cloud_mall_recommend_1;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;

USE cloud_mall_recommend_2;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;

USE cloud_mall_recommend_3;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;

USE cloud_mall_recommend_4;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;

USE cloud_mall_recommend_5;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;

USE cloud_mall_recommend_6;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;

USE cloud_mall_recommend_7;
CREATE TABLE IF NOT EXISTS product_view_record_0 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_1 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_2 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_3 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_4 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_5 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_6 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_7 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_8 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_9 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_10 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_11 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_12 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_13 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_14 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_15 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_16 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_17 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_18 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_19 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_20 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_21 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_22 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_23 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_24 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_25 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_26 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_27 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_28 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_29 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_30 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_31 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_32 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_33 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_34 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_35 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_36 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_37 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_38 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_39 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_40 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_41 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_42 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_43 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_44 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_45 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_46 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_47 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_48 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_49 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_50 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_51 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_52 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_53 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_54 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_55 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_56 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_57 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_58 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_59 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_60 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_61 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_62 LIKE cloud_mall_recommend_0.product_view_record_0;
CREATE TABLE IF NOT EXISTS product_view_record_63 LIKE cloud_mall_recommend_0.product_view_record_0;
